# Generated by Django 4.0 on 2022-01-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=100)),
                ('testImage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
