# Generated by Django 4.0 on 2022-01-19 20:23

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.filename),
        ),
    ]
